name: Build Release
on:
  workflow_dispatch:
permissions: {}
jobs:
  init:
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - 'macos-15'
        platform:
          - 'osx-arm64'
    outputs:
      cache-key: ${{ runner.os }}-cargo-
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cache
        with:
          path: |
            ~/.cargo/
            deps/cargo
            deps/rustup
          key: ${{ runner.os }}-cargo-
      - name: init.sh
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./build/init.sh ${{ matrix.platform }}

  build:
    permissions:
      contents: write
    needs: init
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - 'macos-15'
        platform:
          - 'osx-arm64'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/
            deps/cargo
            deps/rustup
          key: ${{ needs.init.outputs.cache-key }}
          enableCrossOsArchive: true
          fail-on-cache-miss: true
      - name: Install dependencies (macOS)
        run: |
          pip3 install meson ninja packaging --break-system-packages
          brew install automake nasm
      - name: Build ${{ matrix.platform }}
        id: build-release
        run: ./build.sh $(cat LIBVIPS_VERSION) ${{ matrix.platform }}
        env:
          VERSION_LATEST_REQUIRED: "false"
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: libvips-8.16.1-${{ matrix.platform }}.tar.gz
          path: |
            target/
          if-no-files-found: error
